export const EVENT_TEMPLATES = [
  {
    key: "marathon",
    label: "Marathon",
    icon: "\u{1F3C3}",
    defaults: {
      type: "Urban",
      distance: 42.2,
      difficulty: 3,
      badge: "\u{1F3C3}",
      status: "completed",
    },
  },
  {
    key: "ultra50",
    label: "50km Ultra",
    icon: "\u{1F97E}",
    defaults: {
      type: "Ultra",
      distance: 50,
      difficulty: 4,
      badge: "\u{1F97E}",
      status: "completed",
    },
  },
  {
    key: "ultra100",
    label: "100km Ultra",
    icon: "\u{1F525}",
    defaults: {
      type: "Ultra",
      distance: 100,
      difficulty: 5,
      badge: "\u{1F525}",
      status: "completed",
    },
  },
  {
    key: "3peaks",
    label: "3 Peaks",
    icon: "\u{1F3D4}\uFE0F",
    defaults: {
      type: "Mountain",
      distance: 38,
      elevation: 1585,
      difficulty: 4,
      badge: "\u{1F3D4}\uFE0F",
      status: "completed",
    },
  },
  {
    key: "parkrun",
    label: "Parkrun",
    icon: "\u{1F333}",
    defaults: {
      type: "Urban",
      distance: 5,
      difficulty: 1,
      badge: "\u{1F333}",
      status: "completed",
    },
  },
  {
    key: "half",
    label: "Half Marathon",
    icon: "\u{1F3C5}",
    defaults: {
      type: "Urban",
      distance: 21.1,
      difficulty: 2,
      badge: "\u{1F3C5}",
      status: "completed",
    },
  },
  {
    key: "mountain",
    label: "Mountain Hike",
    icon: "\u26F0\uFE0F",
    defaults: {
      type: "Mountain",
      distance: 20,
      elevation: 800,
      difficulty: 3,
      badge: "\u26F0\uFE0F",
      status: "completed",
    },
  },
  {
    key: "10k",
    label: "10K Race",
    icon: "\u{1F3AF}",
    defaults: {
      type: "Urban",
      distance: 10,
      difficulty: 1,
      badge: "\u{1F3AF}",
      status: "completed",
    },
  },
];
